name: Repo Freeze Check

# **What it does**: Prevent pull requests from merging during freezes.
# **Why we have it**: Sometimes we need to freeze deployments for various reasons.
# **Who does it impact**: Anyone working on docs.

on:
  workflow_dispatch:
  merge_group:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - unlocked
    branches:
      - main

permissions:
  contents: read

env:
  FREEZE: ${{ secrets.FREEZE }}

jobs:
  check-freezer:
    if: ${{ github.repository == 'hectorsector/effective-octo-carnival' }}
    name: Prevent merging during deployment freezes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Fail if repo merges are paused
        if: ${{ env.FREEZE == 'true' && github.head_ref != 'repo-sync' }}
        run: |
          echo 'Merges into the "main" branch on this repo are currently paused!'
          exit 1
